version: '3.8'

services:
  analytics-ui:
    build: .
    container_name: analytics-ui
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - gateway_net

networks:
  gateway_net:
    external: true
